package com.kamstercodes.vyla.ui.theme

import androidx.compose.ui.graphics.Color

// Expressive High-Energy Palette
// Light Theme Colors
val primaryLight = Color(0xFFE91E63) // Vibrant Pink
val onPrimaryLight = Color(0xFFFFFFFF)
val primaryContainerLight = Color(0xFFFFD8E4)
val onPrimaryContainerLight = Color(0xFF3E001D)
val secondaryLight = Color(0xFF673AB7) // Vibrant Purple
val onSecondaryLight = Color(0xFFFFFFFF)
val secondaryContainerLight = Color(0xFFE9DDFF)
val onSecondaryContainerLight = Color(0xFF22005D)
val tertiaryLight = Color(0xFF00BCD4) // Vibrant Cyan
val onTertiaryLight = Color(0xFFFFFFFF)
val tertiaryContainerLight = Color(0xFFCBF8FF)
val onTertiaryContainerLight = Color(0xFF001F24)
val errorLight = Color(0xFFBA1A1A)
val onErrorLight = Color(0xFFFFFFFF)
val errorContainerLight = Color(0xFFFFDAD6)
val onErrorContainerLight = Color(0xFF410002)
val backgroundLight = Color(0xFFFDF8F9)
val onBackgroundLight = Color(0xFF201A1B)
val surfaceLight = Color(0xFFFDF8F9)
val onSurfaceLight = Color(0xFF201A1B)
val surfaceVariantLight = Color(0xFFF3DDE1)
val onSurfaceVariantLight = Color(0xFF514347)
val outlineLight = Color(0xFF837377)
val outlineVariantLight = Color(0xFFD5C2C6)
val scrimLight = Color(0xFF000000)
val inverseSurfaceLight = Color(0xFF352F30)
val inverseOnSurfaceLight = Color(0xFFFAEEF0)
val inversePrimaryLight = Color(0xFFFFB1C8)

// Dark Theme Colors
val primaryDark = Color(0xFFFFB1C8)
val onPrimaryDark = Color(0xFF5F0030)
val primaryContainerDark = Color(0xFF8E004A)
val onPrimaryContainerDark = Color(0xFFFFD8E4)
val secondaryDark = Color(0xFFCFBCFF)
val onSecondaryDark = Color(0xFF380093)
val secondaryContainerDark = Color(0xFF4F19A0)
val onSecondaryContainerDark = Color(0xFFE9DDFF)
val tertiaryDark = Color(0xFF4FD8EB)
val onTertiaryDark = Color(0xFF00363D)
val tertiaryContainerDark = Color(0xFF004F58)
val onTertiaryContainerDark = Color(0xFFCBF8FF)
val errorDark = Color(0xFFFFB4AB)
val onErrorDark = Color(0xFF690005)
val errorContainerDark = Color(0xFF93000A)
val onErrorContainerDark = Color(0xFFFFDAD6)
val backgroundDark = Color(0xFF1B1113)
val onBackgroundDark = Color(0xFFF0E0E2)
val surfaceDark = Color(0xFF1B1113)
val onSurfaceDark = Color(0xFFF0E0E2)
val surfaceVariantDark = Color(0xFF514347)
val onSurfaceVariantDark = Color(0xFFD5C2C6)
val outlineDark = Color(0xFF9D8C90)
val outlineVariantDark = Color(0xFF514347)
val scrimDark = Color(0xFF000000)
val inverseSurfaceDark = Color(0xFFF0E0E2)
val inverseOnSurfaceDark = Color(0xFF352F30)
val inversePrimaryDark = Color(0xFFE91E63)
